# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_s00a2s_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_sarn_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_srn_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_m00s2a_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/bd_afc3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/bd_afc3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_s00a2s_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_sarn_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/bd_afc3_srn_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/bd_afc3_m00s2a_0_ooc.xdc

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
