# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
# IP: The module: 'design_1_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
# IP: The module: 'design_1_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/AX7010_2023.1-master/course_s6_linux/17.i2c_test/linux_base/Vivado/linux_base/linux_base.gen/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
